Add user service
RKashanok/jd2-moviebase pull request #12
Opened 2024-09-11 19:48 UTC by siarheima-papaya

2024-09-12 09:51 UTC, RKashanok requested changes

2024-09-12 09:51 UTC, RKashanok commented on pom.xml
> +        </dependency>
по-моему servlet-api подтягивется из зависимости spring-webmvc. Зачем его тянуть еще раз отдельно?

2024-09-12 09:51 UTC, RKashanok commented on src/main/java/com/jd2/moviebase/config/DataSource.java
> +    public DataSource() throws ClassNotFoundException {
Мы же решили сделать его бином и инициализировать сразу в конфиге?

2024-09-12 09:51 UTC, RKashanok commented on src/main/java/com/jd2/moviebase/config/WebAppInitializer.java
> +        root.scan("com.jd2.moviebase");
давай укажем как и где производить сканирование пакетов только в классе конфига WebConfig, а отсюда уберем

2024-09-12 09:51 UTC, RKashanok commented on src/main/java/com/jd2/moviebase/config/WebAppInitializer.java
> +        sc.addListener(new ContextLoaderListener(root));
не нужная строка

2024-09-12 09:51 UTC, RKashanok commented on src/main/java/com/jd2/moviebase/controller/UserController.java
> +    @PostMapping(value = "/create")
убираем "/create"

2024-09-12 09:51 UTC, RKashanok commented on src/main/java/com/jd2/moviebase/controller/UserController.java
> +    @GetMapping(value = "/all")
убираем "/all"

2024-09-12 09:51 UTC, RKashanok commented on src/main/java/com/jd2/moviebase/controller/UserController.java
> +    @PutMapping(value = "/update")
убираем "/update"

2024-09-12 09:51 UTC, RKashanok commented on src/main/java/com/jd2/moviebase/controller/UserController.java
> +    @DeleteMapping(value = "/delete/{id}")
убираем "/delete"

2024-09-12 09:51 UTC, RKashanok commented on src/main/java/com/jd2/moviebase/repository/UserRepository.java
> +                user.setUpdatedAt(resultSet.getDate("updated_at"));
вынеси логику создания юзера из резалт сета в отдельный метож

2024-09-15 09:20 UTC, siarheima-papaya commented on pom.xml
> +        </dependency>
Если удалить эту депенденси, то не находит ServletContext, который используется в WebAppInitializer. И не предлагает откуда можно его импортировать, кроме import jakarta.servlet.ServletContext;

2024-09-15 09:20 UTC, siarheima-papaya commented on src/main/java/com/jd2/moviebase/config/DataSource.java
> +    public DataSource() throws ClassNotFoundException {
Исправил

2024-09-15 09:20 UTC, siarheima-papaya commented on src/main/java/com/jd2/moviebase/config/WebAppInitializer.java
> +        root.scan("com.jd2.moviebase");
Без этой строчки не работает

2024-09-15 09:20 UTC, siarheima-papaya commented on src/main/java/com/jd2/moviebase/config/WebAppInitializer.java
> +        sc.addListener(new ContextLoaderListener(root));
Без этой строчки не работает

2024-09-15 09:21 UTC, siarheima-papaya commented on src/main/java/com/jd2/moviebase/controller/UserController.java
> +    @PostMapping(value = "/create")
Исправил

2024-09-15 09:21 UTC, siarheima-papaya commented on src/main/java/com/jd2/moviebase/controller/UserController.java
> +    @PutMapping(value = "/update")
Исправил

2024-09-15 09:21 UTC, siarheima-papaya commented on src/main/java/com/jd2/moviebase/controller/UserController.java
> +    @DeleteMapping(value = "/delete/{id}")
Исправил

2024-09-15 09:26 UTC, siarheima-papaya commented on src/main/java/com/jd2/moviebase/repository/UserRepository.java
> +                user.setUpdatedAt(resultSet.getDate("updated_at"));
Создал private User getUserObject(ResultSet resultSet)

2024-09-15 09:26 UTC, siarheima-papaya commented on src/main/java/com/jd2/moviebase/controller/UserController.java
> +    @GetMapping(value = "/all")
Исправил

2024-09-17 15:35 UTC, RKashanok approved these changes

2024-09-17 15:35 UTC, RKashanok commented on src/main/java/com/jd2/moviebase/config/WebAppInitializer.java
> +        root.scan("com.jd2.moviebase");
ну в текущем варианте конфигурации - да.

2024-09-17 15:35 UTC, RKashanok commented on src/main/java/com/jd2/moviebase/config/WebAppInitializer.java
> +        sc.addListener(new ContextLoaderListener(root));
ок

2024-09-17 15:35 UTC, RKashanok commented on src/main/java/com/jd2/moviebase/config/WebConfig.java
>  @ComponentScan(basePackages = "com.jd2.moviebase")
напомни рассказать про это вот. у тебя оно дважды укзано

2024-09-17 15:35 UTC, RKashanok approved these changes

2024-09-17 15:46 UTC, merged