Add Account and Comment controllers
RKashanok/jd2-moviebase pull request #13
Opened 2024-09-17 19:40 UTC by siarheima-papaya

2024-09-18 19:12 UTC, RKashanok requested changes

2024-09-18 19:12 UTC, RKashanok commented on src/main/java/com/jd2/moviebase/controller/AccountController.java
> +    @GetMapping("users/{id}")
/users/{id}

2024-09-18 19:12 UTC, RKashanok commented on src/main/java/com/jd2/moviebase/controller/AccountController.java
> +    @PutMapping
@PutMapping("/{id}")

2024-09-18 19:12 UTC, RKashanok commented on src/main/java/com/jd2/moviebase/controller/CommentController.java
> +    @GetMapping()
@GetMapping

2024-09-18 19:12 UTC, RKashanok commented on src/main/java/com/jd2/moviebase/controller/AccountController.java
> +    public Account update(@RequestBody Account account) {
try to use DTO

2024-09-18 19:12 UTC, RKashanok commented on src/main/java/com/jd2/moviebase/controller/CommentController.java
> +    @PutMapping
@PutMapping("/{id}")

2024-09-19 19:08 UTC, siarheima-papaya commented on src/main/java/com/jd2/moviebase/controller/AccountController.java
> +    @GetMapping("users/{id}")
Fixed

2024-09-19 19:08 UTC, siarheima-papaya commented on src/main/java/com/jd2/moviebase/controller/AccountController.java
> +    @PutMapping
Fixed

2024-09-19 19:09 UTC, siarheima-papaya commented on src/main/java/com/jd2/moviebase/controller/AccountController.java
> +    public Account update(@RequestBody Account account) {
Replaced by Dto

2024-09-19 19:09 UTC, siarheima-papaya commented on src/main/java/com/jd2/moviebase/controller/CommentController.java
> +    @PutMapping
Fixed

2024-09-20 19:32 UTC, RKashanok requested changes

2024-09-20 19:32 UTC, RKashanok commented on src/main/java/com/jd2/moviebase/controller/AccountController.java
> +    @GetMapping("/users/{id}")
вот тут лучше не @PathVariable, а @RequestParam. 
Т.е. сделать 
@GetMapping
public Account findByUserId(@RequestParam(name = "userId", required = false) Integer id)
И если есть userId, то фильтровать аккаунты только для этого юзера, если нет - то отдавать все

2024-09-20 19:32 UTC, RKashanok commented on src/main/java/com/jd2/moviebase/controller/AccountController.java
>          return accountService.create(account);
А почему ты Dto только для апдейта добавил, если апдейт и пост - по сути одно и то же )

2024-09-20 19:32 UTC, RKashanok commented on src/main/java/com/jd2/moviebase/controller/AccountController.java
>      public Account findByUserId(@PathVariable("id") Integer id) {
Возвращать нужно везде одно и то же - возвращаешь Dto - возвращай его везде

2024-09-20 19:32 UTC, RKashanok commented on src/main/java/com/jd2/moviebase/controller/CommentController.java
> +    public CommentDto update(@PathVariable("id") Integer id, @RequestBody CommentDto commentDto) {
Аналогично с аккаунтом - если завел Dto, то его и используй

2024-09-20 19:32 UTC, RKashanok commented on src/main/java/com/jd2/moviebase/dto/AccountDto.java
> +public class AccountDto {
если ты на фронтенд будешь возвращать такое Dto, то как фронтенд поймет, какого юзера надо будет удалить/изменить? Он же на id ориентируется

2024-09-20 19:32 UTC, RKashanok commented on src/main/java/com/jd2/moviebase/dto/CommentDto.java
> +    private String note;
аналогично с аккаунтом

2024-09-20 19:32 UTC, RKashanok commented on src/main/java/com/jd2/moviebase/model/Account.java
> +@AllArgsConstructor
если пересел на ломбок, то дабавь в генерацию еще equals и hashCode

2024-09-20 19:32 UTC, RKashanok commented on src/main/java/com/jd2/moviebase/model/AccountMovie.java
> +@NoArgsConstructor
аналогично аккаунту

2024-09-20 19:32 UTC, RKashanok commented on src/main/java/com/jd2/moviebase/model/Comment.java
> +@NoArgsConstructor
смотри выше ))

2024-09-20 19:32 UTC, RKashanok commented on src/main/java/com/jd2/moviebase/model/Genre.java
> +@NoArgsConstructor
-"-

2024-09-24 18:09 UTC, RKashanok requested changes

2024-09-24 18:09 UTC, RKashanok commented on src/main/java/com/jd2/moviebase/controller/AccountController.java
> +        return accountService.findByUserId(id);
а если нет userId? Давай проверять - есть - фильтруем по нему. нет - вызываем без него

2024-09-24 18:09 UTC, RKashanok commented on src/main/java/com/jd2/moviebase/controller/CommentController.java
> +    public ResponseEntity<CommentDto> findById(@PathVariable("id") int id) {
Мы решили не использовать ResponseEntity

2024-09-24 18:09 UTC, RKashanok commented on src/main/java/com/jd2/moviebase/dto/AccountDto.java
> +@EqualsAndHashCode
Все эти аннотации можно заменить аннотацией @Data

2024-09-24 18:09 UTC, RKashanok commented on src/main/java/com/jd2/moviebase/model/User.java
> +@EqualsAndHashCode
У тебя везде разный набор аннотаций. Поставь просто везде @Data, мы не топим сейчас за оптимальное наполнение класса )

2024-09-24 18:09 UTC, RKashanok commented on src/main/java/com/jd2/moviebase/repository/AccountRepository.java
> +    public AccountDto create(AccountDto accountDto) {
Из репозитория должна выходить энтити, а не dto. Dto должна выходить уже из слоя сервисов в контроллер

2024-09-24 18:09 UTC, RKashanok commented on src/main/java/com/jd2/moviebase/repository/AccountRepository.java
> +    private AccountDto getAccountDtoObject(ResultSet resultSet) throws SQLException {
Все конверсии в-из dto стоит делать в утилитном классе. ModelMapper например

2024-10-05 09:47 UTC, siarheima-papaya commented on src/main/java/com/jd2/moviebase/controller/AccountController.java
> +        return accountService.findByUserId(id);
Так есть обработка на уровне Repositories
        return Optional.ofNullable(account)
                .orElseThrow(() -> new RuntimeException("Account with user ID " + userId + " not found"));
                
Не совсем понимаю, зачем что-то другое вызывать, если запрашиваемая сущность не найдена

2024-10-05 09:48 UTC, siarheima-papaya commented on src/main/java/com/jd2/moviebase/dto/AccountDto.java
> +@EqualsAndHashCode
Не работает только с аннтацией Data. Если я создаю конструктор без аргументов, то ругается

2024-10-05 09:49 UTC, siarheima-papaya commented on src/main/java/com/jd2/moviebase/model/User.java
> +@EqualsAndHashCode
Я везде добавил аннотации
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor

2024-10-05 10:08 UTC, siarheima-papaya commented on src/main/java/com/jd2/moviebase/controller/CommentController.java
> +    public ResponseEntity<CommentDto> findById(@PathVariable("id") int id) {
Исправил. Теперь возвращает CommentDto

2024-10-05 10:08 UTC, siarheima-papaya commented on src/main/java/com/jd2/moviebase/repository/AccountRepository.java
> +    public AccountDto create(AccountDto accountDto) {
Исправил

2024-10-05 10:08 UTC, siarheima-papaya commented on src/main/java/com/jd2/moviebase/repository/AccountRepository.java
> +    private AccountDto getAccountDtoObject(ResultSet resultSet) throws SQLException {
Добавил методы в класс ModelMapper

2024-10-05 13:27 UTC, RKashanok approved these changes

2024-10-05 13:27 UTC, merged