Add liquibase
RKashanok/jd2-moviebase pull request #17
Opened 2024-09-22 10:35 UTC by siarheima-papaya

2024-09-24 18:12 UTC, RKashanok requested changes

2024-09-24 18:12 UTC, RKashanok commented on src/main/resources/config/liquibase/20242209-create-casts-table.sql
> +CREATE TABLE IF NOT EXISTS casts (
Замени плиз на реальную таблицу. Users например, или Users и Accounts

2024-09-24 18:44 UTC, siarheima-papaya commented on src/main/resources/config/liquibase/20242209-create-casts-table.sql
> +CREATE TABLE IF NOT EXISTS casts (
Заменил на 
```
CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(50),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
```

2024-09-26 18:00 UTC, RKashanok approved these changes

2024-10-03 19:02 UTC, merged