Write tests for service layer
RKashanok/jd2-moviebase pull request #31
Opened 2024-11-23 19:30 UTC by PavelKazhukhouski

2024-12-03 11:45 UTC, RKashanok requested changes

2024-12-03 11:45 UTC, RKashanok commented on src/test/java/com/jd2/moviebase/service/GenreServiceTest.java
> +    @BeforeEach
вынеси создание в приватные методы

2024-12-03 11:45 UTC, RKashanok commented on src/test/java/com/jd2/moviebase/service/MovieServiceTest.java
> +    void setUp() {
аналогично предыдущему

2024-12-03 11:45 UTC, RKashanok commented on src/main/java/com/jd2/moviebase/controller/UserController.java
> +        UserDetailModel userDetailModel = (UserDetailModel)authentication.getPrincipal();
а для чего эти строки? Ты зачем-то дергаешь контекст, а результат не используешь

2024-12-03 11:45 UTC, RKashanok commented on src/test/java/com/jd2/moviebase/service/AccountMovieServiceTest.java
> +        verify(accountMovieRepository, times(1)).create(any(AccountMovie.class));
тут лучше any(AccountMovie.class) заменить на тот, который ты из метода получаешь. Так ты будешь уверен, что до репозитория дошел именно тот аккаунт что нужен, без изменений по пути

2024-12-03 11:45 UTC, RKashanok commented on src/test/java/com/jd2/moviebase/service/AccountServiceTest.java
> +        verify(accountRepository, times(1)).create(any(Account.class));
как и в предыдущем комменте

2024-12-03 11:45 UTC, RKashanok commented on src/test/java/com/jd2/moviebase/service/CommentServiceTest.java
> +        CommentDto result = commentService.update(1L, getCommentDto());
лучше всегда инициализировать прямо в тесте результат get....() - так можно будет потом проще отдебажить переменные

2024-12-03 14:42 UTC, PavelKazhukhouski commented on src/main/java/com/jd2/moviebase/controller/UserController.java
> +        UserDetailModel userDetailModel = (UserDetailModel)authentication.getPrincipal();
Блин, удалить забыл. Что-то экспериментировал.

2024-12-03 14:43 UTC, PavelKazhukhouski commented on src/test/java/com/jd2/moviebase/service/GenreServiceTest.java
> +    @BeforeEach
Done.

2024-12-03 14:43 UTC, PavelKazhukhouski commented on src/test/java/com/jd2/moviebase/service/MovieServiceTest.java
> +    void setUp() {
Done.

2024-12-10 16:09 UTC, RKashanok approved these changes

2024-12-10 16:09 UTC, RKashanok commented on src/test/java/com/jd2/moviebase/service/AccountMovieServiceTest.java
> +        verify(accountMovieRepository, times(1)).create(getAccountMovie());
@Test
    void create_ShouldCallRepositoryCreateMethod() {
        AccountMovie am = getAccountMovie();
        doNothing().when(accountMovieRepository).create(am);
        accountMovieService.create(am);

        verify(accountMovieRepository, times(1)).create(am);
    }

2024-12-19 01:19 UTC, merged