Add UserRepository, UserService and logger
RKashanok/jd2-moviebase pull request #4
Opened 2024-08-20 07:36 UTC by siarheima-papaya

2024-08-20 07:58 UTC, RKashanok requested changes

2024-08-20 07:58 UTC, RKashanok commented on src/main/java/com/repository/UserRepository.java
> +            PreparedStatement ps = conn.prepareStatement("INSERT INTO users (email, password, role, created_at, updated_at) VALUES (?, ?, ?, ?, ?)");
выдели все SQL в отдельные переменные класса:
private final String CREATE_USER_SQL = "INSERT INTO users (email, password, role, created_at, updated_at) VALUES (?, ?, ?, ?, ?)";
ну и так дальше

2024-08-20 07:58 UTC, RKashanok commented on src/main/java/com/repository/UserRepository.java
> +            PreparedStatement ps = conn.prepareStatement("DELETE FROM users WHERE id = ?");
ну и здесь, как и говорили, нужно сначала пройтись по зависимостям этого юзера. В аккаунт можно кстати тоже добавить поле 'active' и не удалять, а делать active = false.

2024-08-21 14:58 UTC, siarheima-papaya commented on src/main/java/com/repository/UserRepository.java
> +            PreparedStatement ps = conn.prepareStatement("INSERT INTO users (email, password, role, created_at, updated_at) VALUES (?, ?, ?, ?, ?)");
Пофиксил

2024-08-21 14:58 UTC, siarheima-papaya commented on src/main/java/com/repository/UserRepository.java
> +            PreparedStatement ps = conn.prepareStatement("DELETE FROM users WHERE id = ?");
Вроде пофиксил

2024-08-21 19:31 UTC, RKashanok requested changes

2024-08-21 19:31 UTC, RKashanok commented on src/main/java/com/jd2/moviebase/repository/AccountRepository.java
> +            ps.setTimestamp(9, new java.sql.Timestamp(account.getCreatedAt().getTime()));
это лишнее - у тебя же 
`    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,`

2024-08-21 19:31 UTC, RKashanok commented on src/main/java/com/jd2/moviebase/repository/AccountRepository.java
> +            PreparedStatement psComments = conn.prepareStatement(INACTIVE_COMMENT_SQL);
Плохо - для работы с комментариями нужно создать и использовать CommentService. И этот CommentService должен вызываться из AccountService, а не из репозитория (то же самое касается и UserMovie)

2024-08-21 19:31 UTC, RKashanok commented on src/main/java/com/jd2/moviebase/repository/UserRepository.java
> +            psAccounts.executeUpdate();
аналогично коменту выше

2024-08-22 20:22 UTC, siarheima-papaya commented on src/main/java/com/jd2/moviebase/repository/AccountRepository.java
> +            ps.setTimestamp(9, new java.sql.Timestamp(account.getCreatedAt().getTime()));
Удалил

2024-08-22 20:22 UTC, siarheima-papaya commented on src/main/java/com/jd2/moviebase/repository/AccountRepository.java
> +            PreparedStatement psComments = conn.prepareStatement(INACTIVE_COMMENT_SQL);
Изменил

2024-08-22 20:22 UTC, siarheima-papaya commented on src/main/java/com/jd2/moviebase/repository/UserRepository.java
> +            psAccounts.executeUpdate();
Изменил

2024-08-24 08:01 UTC, RKashanok commented on src/main/java/com/jd2/moviebase/repository/AccountRepository.java
> +    public Account findByUserId(int userId) {
`Optioinal<Account>`

2024-08-24 08:01 UTC, RKashanok commented on init.sql
> -            ON DELETE CASCADE,
давай сделаем account_id наллабл

2024-08-24 08:01 UTC, RKashanok commented on src/main/java/com/jd2/moviebase/service/AccountService.java
> +        CommentsService commentsService = new CommentsService(new CommentsRepository(ds));
инициализировать как поле класса (в конструкторе)

2024-08-24 08:01 UTC, RKashanok commented on src/main/java/com/jd2/moviebase/service/UserService.java
> +        CommentsService commentsService = new CommentsService(new CommentsRepository(ds));
аналогично с AccountService

2024-08-26 15:50 UTC, siarheima-papaya commented on src/main/java/com/jd2/moviebase/repository/AccountRepository.java
> +    public Account findByUserId(int userId) {
Добавил

2024-08-26 15:50 UTC, siarheima-papaya commented on init.sql
> -            ON DELETE CASCADE,
Исправил

2024-08-26 15:50 UTC, siarheima-papaya commented on src/main/java/com/jd2/moviebase/service/UserService.java
> +        CommentsService commentsService = new CommentsService(new CommentsRepository(ds));
Исправил

2024-08-26 15:51 UTC, siarheima-papaya commented on src/main/java/com/jd2/moviebase/service/AccountService.java
> +        CommentsService commentsService = new CommentsService(new CommentsRepository(ds));
Исправил

2024-08-26 19:43 UTC, RKashanok commented on src/main/java/com/jd2/moviebase/repository/AccountRepository.java
> +            conn.setAutoCommit(false);
тут не нужно - ты ток одну запись аффектишь в одной таблице

2024-08-26 19:43 UTC, RKashanok commented on src/main/java/com/jd2/moviebase/repository/CommentsRepository.java
> +    private final String DU_NULL_ACC_ID_SQL = "UPDATE comments SET account_id = NULL WHERE account_id = ?";
DU??

2024-08-26 19:43 UTC, RKashanok commented on src/main/java/com/jd2/moviebase/repository/UserRepository.java
> +            conn.setAutoCommit(false);
суть этого автокоммита в том, что бы в одной транзакции менять несколько зависимых записей. У тебя просто создается одна запись в рамках одного коннекшна. Так что здесь смысла от него нет

2024-08-26 19:43 UTC, RKashanok commented on src/main/java/com/jd2/moviebase/service/AccountService.java
> +        commentsService.setNullAccId(id);
почему бы не сделать оба верхних действия в одном запросе?

2024-08-27 06:18 UTC, siarheima-papaya commented on src/main/java/com/jd2/moviebase/repository/AccountRepository.java
> +            conn.setAutoCommit(false);
Пофиксил

2024-08-27 06:19 UTC, siarheima-papaya commented on src/main/java/com/jd2/moviebase/repository/CommentsRepository.java
> +    private final String DU_NULL_ACC_ID_SQL = "UPDATE comments SET account_id = NULL WHERE account_id = ?";
DU HAST :)
Пофиксил

2024-08-27 06:19 UTC, siarheima-papaya commented on src/main/java/com/jd2/moviebase/service/AccountService.java
> +        commentsService.setNullAccId(id);
Смержил два в один

2024-08-28 07:14 UTC, RKashanok approved these changes
Повыноси создание Statement'ов в ресурсы блока try(...)

2024-08-28 07:14 UTC, RKashanok commented on src/main/java/com/jd2/moviebase/repository/AccountRepository.java
>              PreparedStatement ps = conn.prepareStatement(CREATE_SQL, PreparedStatement.RETURN_GENERATED_KEYS);
вынеси создание так же в ресурсы try(...). Если не в курсе что это и зачем - напомни, расскажу при созвоне

2024-08-29 06:33 UTC, merged